# Generated by Django 3.1.2 on 2021-01-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parentMenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menu', verbose_name='父菜单'),
        ),
        migrations.DeleteModel(
            name='ChildrenMenu',
        ),
    ]
