# Generated by Django 3.1.2 on 2021-01-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210104_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parentMenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menu', verbose_name='父菜单'),
        ),
    ]
