# Generated by Django 3.1.2 on 2020-12-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.CreateModel(
            name='ChildrenMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authName', models.CharField(max_length=20)),
                ('path', models.CharField(default='', max_length=128)),
                ('parentMenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.menu')),
            ],
        ),
    ]
