# Generated by Django 3.1.2 on 2021-01-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210104_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuserinfo',
            options={'ordering': ['is_active', 'is_superuser', 'is_staff']},
        ),
    ]
