# Generated by Django 3.1.2 on 2020-12-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201214_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodskind',
            old_name='mainKind',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goodskind',
            old_name='secondKind',
            new_name='parent',
        ),
    ]
