# Generated by Django 3.1.2 on 2021-01-13 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210111_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='introduce',
            field=models.TextField(blank=True, null=True, verbose_name='商家介绍'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='itemClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.goodskind', verbose_name='商品种类'),
        ),
    ]
