# Generated by Django 3.1.2 on 2020-12-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201214_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(default='斤', max_length=5),
            preserve_default=False,
        ),
    ]
