# Generated by Django 3.1.2 on 2021-01-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210113_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.goodsinfo', verbose_name='物品'),
        ),
    ]
