# Generated by Django 3.1.2 on 2020-12-25 01:31

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_goodsinfo_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsimage',
            name='itemID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.goodsinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childrenmenu',
            name='parentMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
        ),
        migrations.AlterField(
            model_name='childrenmenu',
            name='path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to=api.models.item_directory_path),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='itemClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goodskind'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='merchantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchant'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(max_length=128),
        ),
    ]
