# Generated by Django 3.1.2 on 2021-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210114_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='introduce',
            field=models.TextField(blank=True, default='此商品未填写介绍', null=True, verbose_name='商品介绍'),
        ),
    ]
