# Generated by Django 3.1.2 on 2021-01-18 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210117_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbooks',
            name='time',
        ),
        migrations.AddField(
            model_name='cookbooks',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookbooks',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
