# Generated by Django 3.1.2 on 2020-12-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_goodsimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsimage',
            name='name',
            field=models.CharField(default='2', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
