# Generated by Django 3.1.2 on 2021-01-21 22:04

import api.utils.changeName
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210118_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.utils.changeName.changeCarouselPics, verbose_name='图片')),
                ('name', models.CharField(max_length=255, verbose_name='图片名')),
            ],
        ),
    ]
