# Generated by Django 3.1.2 on 2020-12-30 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201228_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='masterid',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.BooleanField(default=False)),
                ('send_status', models.BooleanField(default=False)),
                ('delivery_status', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('deliveryInfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.deliveryinfo')),
            ],
        ),
    ]
