# Generated by Django 3.1.2 on 2021-01-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='订单uuid'),
        ),
    ]
