# Generated by Django 3.1.2 on 2021-01-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210126_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='usable',
            field=models.BooleanField(default=True, verbose_name='地址可用'),
        ),
    ]
