# Generated by Django 3.1.2 on 2021-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_deliveryinfo_usable'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='usable',
            field=models.BooleanField(default=True, verbose_name='商品可用'),
        ),
    ]
