# Generated by Django 3.1.2 on 2020-12-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
